export const endpoints = {
    // Public
    getHeader: "/get-header",
    getFooter: "/get-footer",
    getPages: "/get-pages",
    getPageDetails: "/get-page-details",
    getProducts: "/get-products",
    getProductDetails: "/get-product-details",
    // Auth
    login: "/login",
    logout: "/logout",
    profile: "/profile",
    profileUpdate: "/profile-update",
    changePassword: "/change-password",
    // Pages
    pages: "/admin/pages",
    pageAdd: "/admin/page/add",
    pageEdit: "/admin/page/edit",
    pageUpdate: "/admin/page/update",
    pageSectionImageDelete: "/admin/page-section-image/delete",
    pageSectionDelete: "/admin/page-section/delete",
    pageDelete: "/admin/page/delete",
    // Users
    users: "/admin/users",
    userAdd: "/admin/user/add",
    userEdit: "/admin/user/edit",
    userUpdate: "/admin/user/update",
    userDelete: "/admin/user/delete",
    // Categories
    categories: "/admin/categories",
    categoryAdd: "/admin/category/add",
    categoryEdit: "/admin/category/edit",
    categoryUpdate: "/admin/category/update",
    categoryImageDelete: "/admin/category/delete-image",
    categoryDelete: "/admin/category/delete",
    // Products
    products: "/admin/products",
    productAdd: "/admin/product/add",
    productEdit: "/admin/product/edit",
    productUpdate: "/admin/product/update",
    productImageDelete: "/admin/product/delete-image",
    productSectionImageDelete: "/admin/product-section-image/delete",
    productGalleryDelete: "/admin/product-gallery/delete",
    productSectionDelete: "/admin/product-section/delete",
    productDelete: "/admin/product/delete",
    // Settings
    settings: "/admin/settings",
    settingsUpdate: "/admin/settings",
}